spring:
  application:
    name: LoansBackApp
  datasource:
    url: jdbc:postgresql://localhost:5432/loans_db
    username: postgres
    password: admin123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8030
  servlet:
    context-path: /api/v1
logging:
  level:
    org:
      springframework:
        web : trace


